version: "1.1"

services:
  backend:
    build: .
    volumes:
      - ./:/backend
    env_file:
      - .env
    command: >
      uvicorn app:application --host 0.0.0.0 --port 5001 --reload --workers 2
    restart: on-failure
    ports:
      - "5001:5001"
